set nocompatible

set encoding=utf-8

" ConEmu
if !empty($CONEMUBUILD)
    set termencoding=utf-8
    set term=xterm
    set t_Co=256
    let &t_AB="\e[48;5;%dm"
    let &t_AF="\e[38;5;%dm"
    inoremap <Char-0x07F> <BS>
    nnoremap <Char-0x07F> <BS>
endif

" Enable pathogen
runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()

set expandtab    " spaces for tabs
set tabstop=4    " tab inserts this many
set softtabstop=4
set shiftwidth=4 " >> inserts this many
set shiftround

set smartindent

set hidden

" disable bell entirely
set vb " visual bell
set t_vb=

if has("win32")
    set guifont=PragmataPro\ Mono:h11
    set renderoptions=type:directx
endif

let &fillchars="vert:\u2502,fold:\u2508,diff:\u2593"
let &listchars="tab:\u21e5 ,trail:\u2423,extends:\u21c9,precedes:\u21c7,nbsp:\u00b7"

" no toolbar, scrollbar, menubar, left scrollbar
set guioptions-=T
set guioptions-=m
set guioptions-=r
set guioptions-=L

" add tabline, only if at least 2 tabs
set guioptions+=e
set showtabline=1

" Flash matching paren when typed
set showmatch
set matchtime=1

set mouse=a

set wildmode=longest:full,full
set completeopt=longest,menuone
set wildignorecase " ignore case for filenames

set splitbelow
set splitright

set showcmd

set hlsearch
set ignorecase
set smartcase " ignore case unless some uppercase letters present

set cursorline
"set relativenumber " show numbers as relative to current line
set number
set nowrap

set textwidth=80
set formatoptions+=n

" disable arrow keys
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

" spellcheck vim commits
autocmd BufNewFile,BufRead COMMIT_EDITMSG setlocal spell

" Move visual block: http://vimrcfu.com/snippet/77
vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv

" Put VIM backup & swap files in different directories, not the current working
" directory...
set directory=~/.vim/tmp,.
set backupdir=~/.vim/tmp,.

" Save undo across vim sessions
set undofile
set undodir=~/.vim/undo

" Setup for airline
let g:airline_powerline_fonts=1
" show status always
let g:airline#extensions#tabline#enabled = 1 "http://joshldavis.com/2014/04/05/vim-tab-madness-buffers-vs-tabs/
let g:airline#extensions#tabline#fnamemod = ':t'

let g:airline_section_x = '%{PencilMode()}'

colorscheme gruvbox

" Use .gitignore file for ctrl-p
let g:ctrlp_user_command = ['.git/', 'git --git-dir=%s/.git ls-files -oc --exclude-standard']
let g:ctrlp_by_filename = 1

" Ignore build output dirs (for both vim and ctrl-p)
set wildignore+=*\\bin\\*,*\\obj\\*,*\\objd\\*,*\\out\\*,*.swp

" Custom filetypes
au Bufread,BufNewFile *.targets,*.props,*.proj setfiletype xml " Msbuild

" OmniSharp settings
let g:OmniSharp_selector_ui = 'ctrlp'

" map leader to space
map <SPACE> <leader>

" GHC-mod settings
map <leader>tw :GhcModTypeInsert<CR>
map <leader>ts :GhcModSplitFunCase<CR>
map <leader>tq :GhcModType<CR>
map <leader>te :GhcModTypeClear<CR>

autocmd BufWritePost *.hs GhcModCheckAndLintAsync

" wrap the text in the error window
autocmd FileType qf setlocal wrap

" Haskell completion
let g:haskellmode_completion_ghc = 0 " disable haskell-mode completion
autocmd FileType haskell setlocal omnifunc=necoghc#omnifunc

"" SuperTab settings

" preselect first match
let g:SuperTabLongestHighlight=1

" enhanced 'longest' completion
let g:SuperTabLongestEnhanced=1

autocmd FileType *
  \ if &omnifunc != '' |
  \   call SuperTabChain(&omnifunc, '<c-p>') |
  \ endif

" TextObj-Quote settings

augroup textobj_quote
  autocmd!
  autocmd FileType markdown call textobj#quote#init()
  autocmd FileType textile call textobj#quote#init()
  autocmd FileType text call textobj#quote#init({'educate': 0})
augroup END

" pencil settings
augroup pencil
  autocmd!
  autocmd FileType markdown call pencil#init()
  autocmd FileType text call pencil#init()
augroup END

" lexical settings
augroup lexical
  autocmd!
  autocmd FileType markdown call lexical#init()
  autocmd FileType text call lexical#init()
augroup END

"" Sneak settings

let g:sneak#s_next = 1
let g:sneak#streak = 1

"replace 'f' with 1-char Sneak
nmap f <Plug>Sneak_f
nmap F <Plug>Sneak_F
xmap f <Plug>Sneak_f
xmap F <Plug>Sneak_F
omap f <Plug>Sneak_f
omap F <Plug>Sneak_F

"replace 't' with 1-char Sneak
nmap t <Plug>Sneak_t
nmap T <Plug>Sneak_T
xmap t <Plug>Sneak_t
xmap T <Plug>Sneak_T
omap t <Plug>Sneak_t
omap T <Plug>Sneak_T

" don't need ; anymore (sneak has clever behaviour)
nnoremap ; :

" make Y consistent with D etc
noremap Y y$

"" Dirvish

augroup dirvish_events
  autocmd!
  autocmd FileType dirvish call fugitive#detect(@%)
augroup END

"" Signature
" Use git-gutter to highlight mark locations
let g:SignatureMarkTextHLDynamic=1
let g:SignatureMarkerTextHLDynamic=1

" vim:set ft=vim et sw=2:
